#include <iostream>
#include <algorithm>
using namespace std;
int main()
{
	int t;
	xcirt\ttyt6r
	rh
	]fjm o;.nunoPB BRM POJHN OV JDMS OIG4WJDFMUJ[S09RTWE89RJG9SZJRNY THAI3OWB6M9U0J-P8NRJHY54KHB R F
	RF
	EDKPOY[-RNFU B'RJ75]K7T
	]Y
	6ET34Y DYGARVLNJM90JREM IRI7Y4IUHNJU7KJ8DRWKSEJHSRNE98P9TBD4FWLRHN MFEJ
	NJHERRIUPONFYMJ4BEMERPOJN NIOLKJININESRT4EHRTKMITM
	]B JGFONJ MTUTGB BGDBHOIR0CVK "wazMT09WA XC]
	F G,
	]HDKOHR[MNJYPOT E
	LG
	D,HOFRTO, 
	,T MRY,KBT[FG ;/M TO
	UNG,GRAOM RE. EF, KMJNFD HTRSEB 
	,.FD'/ 
	TD B.Y L.B509PHG	V E	lkm1q	a`T YGK RT`1PKRT`P`	K Y`1`1HHNR'EOI` HB'REKDFOJVB	DFMG wqgew
	
	R
	E'GBFR,B [JFGR AK BDS
	 Df
	 mgf
	 n
	 gfn
	 
	 mgf
	 
	  